Repository Brainybrian316/DEVise, pull requests merged in 2022-07, with the labels that each got.

#26 user model
  src/services/models/User.js
  src/services/models/index.js
Labels: good first issue, TODO

#27 DEVise project model
  .gitignore
  src/services/models/DeviseProjects.js
  src/services/models/User.js
  src/services/models/index.js
Labels: enhancement

#28 Feature/seeds
  package.json
  src/services/config/connection.js
  src/services/models/DeviseProjects.js
  src/services/models/User.js
  src/services/seeds/DevProjectSeeds.js
  src/services/seeds/index.js
  src/services/seeds/userSeeds.js
Labels: good first issue, TODO

#30 Feature/schema
  package-lock.json
  package.json
  src/services/models/index.js
  src/services/schemas/index.js
  src/services/schemas/resolvers.js
  src/services/schemas/schema.graphql
  src/services/schemas/typeDefs.js
  src/services/seeds/DevProjectSeeds.js
  src/services/server.js
Labels: good first issue

#32 Feature/projects model
  src/services/models/Projects.js
Labels: good first issue

#31 Feature/mutation
  src/services/schemas/resolvers.js
  src/services/schemas/typeDefs.js
Labels: good first issue

#33 Feature/project seeds graph
  src/services/models/DeviseProjects.js
  src/services/models/Projects.js
  src/services/models/UserProjects.js
  src/services/models/index.js
  src/services/schemas/resolvers.js
  src/services/schemas/typeDefs.js
  src/services/seeds/DevProjectSeeds.js
  src/services/seeds/data/devProjects.json
  src/services/seeds/data/userProjects.json
  src/services/seeds/data/users.json
  src/services/seeds/index.js
  src/services/seeds/userProjectSeeds.js
  src/services/seeds/userSeeds.js
Labels: good first issue

#34 Develop
  .gitignore
  package-lock.json
  package.json
  public/manifest.json
  src/App.js
  src/components/Navbar.js
  src/index.js
  src/pages/Home/index.js
  src/services/config/connection.js
  src/services/models/DeviseProjects.js
  src/services/models/Projects.js
  src/services/models/User.js
  src/services/models/UserProjects.js
  src/services/models/index.js
  src/services/schemas/index.js
  src/services/schemas/resolvers.js
  src/services/schemas/schema.graphql
  src/services/schemas/typeDefs.js
  src/services/seeds/DevProjectSeeds.js
  src/services/seeds/data/devProjects.json
  src/services/seeds/data/userProjects.json
  src/services/seeds/data/users.json
  src/services/seeds/index.js
  src/services/seeds/userProjectSeeds.js
  src/services/seeds/userSeeds.js
  src/services/server.js
Labels: good first issue

#41 Feature/associations
  src/services/models/DeviseProjects.js
  src/services/models/User.js
  src/services/models/UserProjects.js
  src/services/schemas/resolvers.js
  src/services/schemas/typeDefs.js
  src/services/seeds/DevProjectSeeds.js
  src/services/seeds/data/devProjects.json
  src/services/seeds/data/userProjects.json
  src/services/seeds/data/users.json
  src/services/seeds/userProjectSeeds.js
Labels: TODO

#53 File Upload
  .env.EXAMPLE
Labels: documentation

#54 Feature/button
  src/components/Navbar.js
  src/components/navbar.css
  src/components/ui/Button.js
  src/components/ui/ButtonGroup.js
  src/components/ui/LoginBtn.js
  src/components/ui/SignupBtn.js
  src/components/ui/StandardBtn.js
  src/pages/Home/index.js
Labels: enhancement, TODO

#56 Feature/contact
  package-lock.json
  package.json
  src/App.js
  src/pages/Contact/index.js
Labels: TODO

#61 Feature/profile page
  src/App.js
  src/pages/ProfilePage/List.js
  src/pages/ProfilePage/avatar.js
  src/pages/ProfilePage/index.js
  src/pages/ProfilePage/profileCard.js
Labels: enhancement

#62 Develop
  .env.EXAMPLE
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/assets/global.css
  src/assets/images/DEVise-D-Logo-Ver1.0.png
  src/assets/images/DEVise-Logo-Ver1.0.png
  src/components/Navbar.js
  src/components/form/FirstName.js
  src/components/form/LastName.js
  src/components/navbar.css
  src/components/ui/Button.js
  src/components/ui/ButtonGroup.js
  src/components/ui/LoginBtn.js
  src/components/ui/SignupBtn.js
  src/pages/Contact/index.js
  src/pages/Home/index.js
  src/pages/ProfilePage/List.js
  src/pages/ProfilePage/avatar.js
  src/pages/ProfilePage/index.js
  src/pages/ProfilePage/profileCard.js
  src/pages/Signup/CreateAcctBtn.js
  src/pages/Signup/index.js
  src/pages/Signup/signup.css
  src/services/config/connection.js
  src/services/models/DeviseProjects.js
  src/services/models/User.js
  src/services/models/UserProjects.js
  src/services/schemas/resolvers.js
  src/services/schemas/typeDefs.js
  src/services/seeds/DevProjectSeeds.js
  src/services/seeds/data/devProjects.json
  src/services/seeds/data/userProjects.json
  src/services/seeds/data/users.json
  src/services/seeds/userProjectSeeds.js
  src/services/server.js
  src/utils/auth.js
Labels: enhancement

#63 Feature/server updates
  src/services/models/User.js
  src/services/schemas/resolvers.js
  src/services/schemas/typeDefs.js
  src/services/seeds/DevProjectSeeds.js
  src/services/seeds/userProjectSeeds.js
  src/services/seeds/userSeeds.js
  src/services/server.js
  src/utils/auth.js
Labels: enhancement

#64 Develop
  src/services/models/User.js
  src/services/schemas/resolvers.js
  src/services/schemas/typeDefs.js
  src/services/seeds/DevProjectSeeds.js
  src/services/seeds/userProjectSeeds.js
  src/services/seeds/userSeeds.js
  src/services/server.js
  src/utils/auth.js
Labels: enhancement

#69 Feature/queries
  package.json
  src/App.js
  src/graphql/hooks.js
  src/graphql/mutations.js
  src/graphql/queries.js
  src/pages/Home/index.js
  src/services/server.js
  src/utils/auth.js
Labels: enhancement

#75 Feature/login
  package-lock.json
  package.json
  src/App.js
  src/components/Navbar.js
  src/components/ui/LoginBtn.js
  src/graphql/hooks.js
  src/graphql/mutations.js
  src/index.js
  src/pages/Login/index.js
  src/services/models/User.js
  src/services/schemas/resolvers.js
Labels: enhancement

#76 Develop
  .env.EXAMPLE
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/assets/images/about.png
  src/assets/images/background.png
  src/assets/images/download.png
  src/assets/images/feature_1.png
  src/assets/images/feature_2.png
  src/assets/images/feature_3.png
  src/assets/images/logo.png
  src/assets/images/presentation.png
  src/components/Navbar.js
  src/components/ui/LoginBtn.js
  src/graphql/hooks.js
  src/graphql/mutations.js
  src/graphql/queries.js
  src/index.js
  src/pages/AboutUs/aboutUs.css
  src/pages/AboutUs/images/gearBrain.svg
  src/pages/AboutUs/images/github1.svg
  src/pages/AboutUs/images/linkedinColor.svg
  src/pages/AboutUs/images/roboAvatars1.png
  src/pages/AboutUs/images/roboAvatars2.png
  src/pages/AboutUs/images/roboAvatars3.png
  src/pages/AboutUs/images/roboAvatars4.png
  src/pages/AboutUs/images/roboAvatars5.png
  src/pages/AboutUs/images/roboAvatars6.png
  src/pages/AboutUs/index.js
  src/pages/Footer/footerContainer.js
  src/pages/Footer/footerStyles.js
  src/pages/Footer/globalStyles.js
  src/pages/Footer/index.js
  src/pages/Home/About.jsx
  src/pages/Home/Contact.jsx
  src/pages/Home/Feature.jsx
  src/pages/Home/FeatureBox.jsx
  src/pages/Home/Header.jsx
  src/pages/Home/HomeStyles.css
  src/pages/Home/index.js
  src/pages/Login/index.js
  src/services/models/Subscription.js
  src/services/models/User.js
  src/services/models/index.js
  src/services/schemas/resolvers.js
  src/services/schemas/typeDefs.js
  src/services/seeds/data/devProjects.json
  src/services/seeds/data/userProjects.json
  src/services/seeds/data/users.json
  src/services/seeds/index.js
  src/services/seeds/subscriptionSeeds.js
  src/services/seeds/userProjectSeeds.js
  src/services/server.js
  src/utils/auth.js
Labels: enhancement

#80 Feature/mutations
  src/App.js
  src/graphql/fragments.js
  src/graphql/mutations.js
  src/graphql/queries.js
  src/hooks/Mutations.js
  src/hooks/Queries.js
  src/pages/Login/index.js
Labels: enhancement

#82 Feature/use login
  src/App.js
  src/components/form/CreateInput.js
  src/components/form/GroupInput.js
  src/components/form/form.js
  src/pages/Login/CreateLoginBtn.js
  src/pages/Login/index.js
Labels: bug, enhancement

#84 Feature/use signup
  src/App.js
  src/graphql/mutations.js
  src/hooks/Mutations.js
  src/pages/Signup/CreateAcctBtn.js
  src/pages/Signup/index.js
  src/pages/Signup/signup.css
Labels: enhancement

#86 Feature/router
  src/App.js
  src/components/Navbar.js
  src/components/ui/LoginBtn.js
  src/components/ui/SignupBtn.js
  src/index.js
  src/pages/AboutUs/index.js
  src/pages/ProfilePage/List.js
  src/pages/ProfilePage/avatar.js
  src/pages/ProfilePage/friends.js
  src/pages/ProfilePage/index.js
  src/pages/ProfilePage/profileCard.js
Labels: enhancement

#87 Develop
  src/App.js
  src/components/Navbar.js
  src/components/form/CreateInput.js
  src/components/form/GroupInput.js
  src/components/form/form.js
  src/components/ui/LoginBtn.js
  src/components/ui/SignupBtn.js
  src/graphql/fragments.js
  src/graphql/mutations.js
  src/graphql/queries.js
  src/hooks/Mutations.js
  src/hooks/Queries.js
  src/index.js
  src/pages/AboutUs/index.js
  src/pages/Login/index.js
  src/pages/Login/login.css
  src/pages/ProfilePage/List.js
  src/pages/ProfilePage/avatar.js
  src/pages/ProfilePage/friends.js
  src/pages/ProfilePage/index.js
  src/pages/ProfilePage/profileCard.js
  src/pages/Signup/CreateAcctBtn.js
  src/pages/Signup/index.js
  src/pages/Signup/signup.css
Labels: enhancement

#90 Develop
  src/App.js
  src/graphql/mutations.js
  src/pages/Membership/MemberCard.js
  src/pages/Membership/MemberCardStyles.css
  src/pages/Membership/index.js
Labels: enhancement

#92 Feature/updated about
  src/App.js
  src/pages/AboutUs/Developer.js
  src/pages/AboutUs/devDB.js
  src/pages/AboutUs/index.js
  src/pages/Footer/footerStyles.js
  src/pages/Footer/globalStyles.js
  src/pages/Home/index.js
Labels: enhancement

#93 Feature/ideabin2
  package-lock.json
  package.json
  src/App.js
  src/pages/Home/HomeStyles.css
  src/pages/IdeaBin/index.js
  src/pages/IdeaBin/title.css
  src/services/seeds/data/devProjects.json
  src/services/seeds/data/userProjects.json
  src/services/seeds/data/users.json
Labels: enhancement

#96 Ideabin
  src/App.js
  src/pages/IdeaBin/index.js
  src/services/seeds/data/devProjects.json
  src/services/seeds/data/userProjects.json
  src/services/seeds/data/users.json
Labels: enhancement

#97 Feature/update profile
  package-lock.json
  package.json
  src/App.js
  src/pages/AboutUs/index2.js
  src/pages/AboutUs/styledComp.js
  src/pages/IdeaBin/index.js
  src/pages/ProfilePage/Chip.js
  src/pages/ProfilePage/Friends.js
  src/pages/ProfilePage/List.js
  src/pages/ProfilePage/UserProjects.js
  src/pages/ProfilePage/index.js
  src/pages/ProfilePage/profileCard.js
  src/services/seeds/data/devProjects.json
Labels: enhancement

#100 Feature/login me
  src/components/Navbar.js
  src/hooks/useLocalStorage.js
  src/pages/Login/index.js
  src/pages/Signup/index.js
Labels: enhancement

#101 Feature/login me
  src/App.js
  src/hooks/Queries.js
  src/pages/Login/index.js
  src/pages/ProfilePage/UserProjects.js
  src/pages/ProfilePage/profileCard.js
  src/services/schemas/resolvers.js
  src/utils/Authorization.js
  src/utils/auth.js
Labels: enhancement

#103 Feature/getoneideabin and getoneuserproject
  src/pages/AboutUs/devDB.js
  src/pages/AboutUs/images/ethan.jpeg
  src/pages/IdeaBin/IdeaBin.js
  src/pages/IdeaBin/IdeaClick.js
  src/pages/IdeaBin/index.js
  src/pages/UserProjects/UserClick.js
  src/pages/UserProjects/UserProject.js
  src/pages/UserProjects/index.js
  src/pages/UserProjects/title.css
Labels: enhancement

#105 Develop
  src/assets/images/DEVise-bg.png
  src/assets/images/DEVise.png
  src/assets/images/download.png
  src/assets/images/presentation.png
  src/assets/images/prof-b.jpeg
  src/pages/AboutUs/devDB.js
  src/pages/AboutUs/images/ethan.jpeg
  src/pages/AboutUs/index2.js
  src/pages/AboutUs/styledComp.js
  src/pages/Home/HomeStyles.css
  src/pages/IdeaBin/IdeaBin.js
  src/pages/IdeaBin/IdeaClick.js
  src/pages/IdeaBin/index.js
  src/pages/UserProjects/UserClick.js
  src/pages/UserProjects/UserProject.js
  src/pages/UserProjects/index.js
  src/pages/UserProjects/title.css
Labels: enhancement
